version: '3.9'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    volumes:
      - /app/node_modules # Prevent overwriting node_modules
    environment:
      - WATCHPACK_POLLING=true