version: "3.9"

services:
  flask-app:
    build:
      context: .
    ports:
      - "5001:5000"
    volumes:
      - ./app:/app
    env_file:
      - .env  # Load environment variables from the .env file
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}  # Root password pulled from .env
      MYSQL_DATABASE: ${MYSQL_DB}            # Database name pulled from .env
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
